userlib/console: use `$crate` in macro definitions
Every time `println!` is used, it is necessary to import `print!`, as
it is used internally by the macro.

Without it, the following error arises:
```
error: cannot find macro `print` in this scope
  --> user/lib/src/console.rs:44:23
   |
44 |     ($($arg:tt)*) => (print!("{}\n", format_args!($($arg)*)));
   |                       ^^^^^
   |
  ::: user/lib/src/testing.rs:7:5
   |
7  |     println!("running {} user tests", test_cases.len());
   |     ---------------------------------------------------
					in this macro invocation
   |
   = help: have you added the `#[macro_use]` on the module/import?
   = note: this error originates in the macro `println` (in Nightly
	builds, run with -Z macro-backtrace for more info)
help: consider importing this macro through its public re-export
  --> user/lib/src/testing.rs:3:1
   |
3  + use crate::print;
   |
```

The same happens when using `print!` as it requires `console_print`.

Prefix `console_print` and `print!` with `$crate` inside the macro
definitions to ensure that they uses the correct path without requiring
the imports.

Suggested-by: Stefano Garzarella <sgarzare@redhat.com>
Signed-off-by: Nicola Ramacciotti <niko.ramak@gmail.com>